name: StickyGridLayout
options:
  bundleIdPrefix: com.mingfengho
  deploymentTarget:
    iOS: "12.0"
    tvOS: "12.0"
  createIntermediateGroups: true
settings:
  base:
    GENERATE_INFOPLIST_FILE: YES
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  StickyGridLayout:
    type: framework
    platform: [iOS, tvOS]
    sources:
      - Sources/StickyGridLayout
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mingfengho.StickyGridLayout
        APPLICATION_EXTENSION_API_ONLY: true
    scheme:
      testTargets:
        - StickyGridLayoutTests_${platform}
  StickyGridLayoutTests:
    type: bundle.unit-test
    platform: [iOS, tvOS]
    sources:
      - Tests/StickyGridLayoutTests
    dependencies:
      - target: StickyGridLayout_${platform}
